name: Terraform CI/CD for Proxmox

on:
  push:
    branches:
      - main  # Run this workflow when changes are pushed to the main branch
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.3

      # Step 3: Set up environment variables
      - name: Set Environment Variables
        env:
          TF_VAR_pm_api_url: ${{ secrets.PROXMOX_API_URL }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PROXMOX_API_TOKEN }}
          TF_VAR_pm_api_token_id: ${{ secrets.PROXMOX_API_TOKEN_ID }}
        run: |
          echo "Environment variables set"
          echo "Proxmox URL: $TF_VAR_pm_api_url"  # Avoid echoing secrets

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Adjust this path if needed

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform
        env:
          TF_LOG: DEBUG
          TF_LOG_PATH: /tmp/terraform.log
      
      # TEMP
      - name: Upload Terraform Logs
        uses: actions/upload-artifact@v2
        with:
          name: terraform-logs
          path: /tmp/terraform.log

      # Step 6: Terraform Apply (manual approval required)
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          TF_VAR_pm_api_url: ${{ secrets.PROXMOX_API_URL }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PROXMOX_API_TOKEN }}
          TF_VAR_pm_api_token_id: ${{ secrets.PROXMOX_API_TOKEN_ID }}
